# Generated by Django 4.1 on 2022-08-08 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=12)),
                ('product_ID', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MaxLengthValidator(8)])),
            ],
        ),
    ]
