# Generated by Django 4.1 on 2022-08-08 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market_product',
            name='product_ID',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.MaxLengthValidator(8)]),
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.ManyToManyField(to='app.market_product')),
            ],
        ),
    ]
