# Generated by Django 4.1 on 2022-08-08 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_market_product_product_id_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market_product',
            name='product_ID',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.MaxLengthValidator(8), django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'only alpha numeric characters are allowed')]),
        ),
    ]
