# Generated by Django 4.1 on 2022-08-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_market_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='name',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='market_product',
            name='name',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='market_product',
            name='product_name',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
